name = "backend"
main = "src/index.ts"
compatibility_date = "2025-01-18"
compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "D1"
database_name = "note_anything_db"
database_id = "2c7d47e7-53e8-401e-90e7-5d2936866f2a"
migrations_dir = "drizzle"




# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1