name = "backend"
main = "src/index.ts"
compatibility_date = "2025-01-18"

# compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "note_anything_db"
database_id = "596ed2a2-c0ff-4c47-9f38-6546bc573381"
migrations_dir = "drizzle/migrations"



# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1